// Put a nft collection into the array to show in the gallery page.
export const collection = [
  {
    name: 'genius edition',
    description: '',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t,tsU33UT3K2JTfLgHUo7hdzRhRe4wth885cqVbM8WLiq',
    owner_name: null,
    contract: null,
    token: '28qnjJqxMeVJFRyNDp8yfGwd5DRsRYtoUnQncHWtyfRb',
    image: 'https://bafybeieyryht57micwkrh5lh7gxkowmpyqkyeu7ldvzefbcnaqstl5qeiy.ipfs.dweb.link?ext=png',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: true,
    traits: [
      {
        name: 'darkblock-id',
        value: 'Eaw4uaBnij0tgA8QpeyIOBixcZeDXFxBSVljEA3uEtw',
      },
    ],
  },
  {
    name: 'DB Test Manifesto x 100',
    description: '',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t,tsU33UT3K2JTfLgHUo7hdzRhRe4wth885cqVbM8WLiq',
    owner_name: null,
    contract: null,
    token: '2ARPZA8WqtScekVgWHXTVHG4qM9oFoAWB7gqeZ5fW3QA',
    image: 'https://bafybeiabferucjkqx4coxq2nr6xt24i5zrjvuxvgbhc2wtvaidoevycqi4.ipfs.dweb.link?ext=png',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: true,
    traits: [
      {
        name: 'darkblock-id',
        value: '77VhoOd7jHPq9xc99Ru-J5II5V-bCgH5achXn34fTgA',
      },
    ],
  },
  {
    name: 'Psycho #1258',
    description:
      'Collection of 3000 hand-drawn psychos. Each Psycho your access to alpha, dashboard\n& more future utilities.',
    creator_name: null,
    creator_address: 'A1kkw6eKnZxCWR2nAhd8bz2GmLnz7Nj96QBnxmbg6gfJ',
    owner_name: null,
    contract: null,
    token: '2AZDd6fdRSNN4fxfX57mVdmEMw93MDn9hPu3kJXjaiYa',
    image: 'https://nftstorage.link/ipfs/bafybeial6c6yn7ist4fvofgukrltqgxw67ub4v2toypiwb6nsgjbfjcgrm/289.png',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: false,
    traits: [
      {
        name: 'Background',
        value: 'Grey',
      },
      {
        name: 'Clothes',
        value: 'Dark Shirt',
      },
      {
        name: 'Skin',
        value: 'Skeleton',
      },
      {
        name: 'Beard',
        value: 'Green',
      },
      {
        name: 'Headwear',
        value: 'Marsh Horns',
      },
      {
        name: 'Mouth',
        value: 'Venom',
      },
      {
        name: 'Eyes',
        value: 'Yellow Lightning',
      },
      {
        name: 'Rarity Rank',
        value: 1554,
      },
    ],
  },
  {
    name: 'bunny6',
    description: 'looong',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t',
    owner_name: null,
    contract: null,
    token: '3AHqLon5HbdYu81FUwSRGL2rN4a9x35GyZoKngivPUxV',
    image: 'https://www.arweave.net/rqpLrLhpFN_wbTH_u9HQoCuuH751TW3Sq-LW_cGM_LE?ext=gif',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: true,
    traits: [
      {
        name: 'darkblock-id',
        value: 'KkO-tjsZ5vpe-mtkbPadEU738Wpnw8CqJ1L5Q9ptMWw',
      },
    ],
  },
  {
    name: 'zip',
    description: 'zip test',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t',
    owner_name: null,
    contract: null,
    token: '3hbLVAyZDDT37L5DDYdPXDHEDq3SpcJ3x3TYXqiTXkuw',
    image: 'https://www.arweave.net/ilDJkLNfFxrM1Ilvt1E1mLwL8NwuTgl_Ll4VirWc0mA?ext=PNG',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: true,
    traits: [
      {
        name: 'darkblock-id',
        value: 'M9AiXnlG2OkMIIUvU5P7OXZEr67dYKgB2clplid25TU',
      },
    ],
  },
  {
    name: 'Sigh Ducks Gen 0: Dook #324',
    description: "We should've never swam in that pond.. dook dook.",
    creator_name: null,
    creator_address:
      'B7sjutDWFMjkqSJPCzSSdhFDLtgoMGYtPz1UazcYg7dB,EMnr7f2ziCNBZKkomhssV9s9CETiR23KwzAKumjNULii,RRUMF9KYPcvNSmnicNMAFKx5wDYix3wjNa6bA7R6xqA',
    owner_name: null,
    contract: null,
    token: '412EiTpy6Uee5uB1GktpmTJaCUgFgDKLZDKQ419DCAGK',
    image: 'https://www.arweave.net/3t3F3qlLhbVSQOlS_DAqAxf2RnbhNHii6Z2Rv3YHYUk?ext=png',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: true,
    traits: [
      {
        name: 'Background',
        value: 'Solana',
      },
      {
        name: 'Secret_Treasure',
        value: 'Golden-Egg',
      },
      {
        name: 'Wings',
        value: 'None',
      },
      {
        name: 'Feet',
        value: 'Yellow',
      },
      {
        name: 'Footwear',
        value: 'None',
      },
      {
        name: 'Body',
        value: 'Purple',
      },
      {
        name: 'Ruffle',
        value: 'Leopard',
      },
      {
        name: 'Clothes',
        value: 'None',
      },
      {
        name: 'Head',
        value: 'Purple',
      },
      {
        name: 'Eyes',
        value: 'Stoned',
      },
      {
        name: 'Eyewear',
        value: 'None',
      },
      {
        name: 'Hats',
        value: 'Knight-Helmet',
      },
      {
        name: 'Beak',
        value: 'Orange',
      },
      {
        name: 'Hand',
        value: 'Red-Surf-Board',
      },
    ],
  },
  {
    name: "what's in there?",
    description: 'oh yeah',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t',
    owner_name: null,
    contract: null,
    token: '4RyJgukjoxocXWhfYe16F8Fq7ZwZrYo6a9Nq7KnhVuA4',
    image: 'https://www.arweave.net/5KSDHidPIy-w4-GvsLRCXrA08dcd7YCe2MSmsiJRUbo?ext=jpg',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: false,
    traits: null,
  },
  {
    name: 'Square 01',
    description: 'Testing collections',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t',
    owner_name: null,
    contract: null,
    token: '4rjjWF6qzdFNVxVaEbGSajQ32URRcArhmMKxByX8GqsF',
    image: 'https://www.arweave.net/arXq9yqTEMHmM3zvJTsMak2IY6CxlJNCus8u-f5LDOQ?ext=PNG',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: true,
    traits: [
      {
        name: 'Shape',
        value: 'Square',
      },
    ],
  },
  {
    name: 'Buddy#1',
    description:
      'Oh you only have a 2D Bored Ape? Make your PFP more than just your next twitter avatar. (Darkblock PFP case study)',
    creator_name: null,
    creator_address: 'DBBd3jzbBA6xjfgLH4fkrTdinZRy2teMS2AuBQ6wYQhj',
    owner_name: null,
    contract: null,
    token: '5EnY3TcrzyKKRsCQ5EXGNuW55XaPgbgecD85HoRM6HBc',
    image: 'ipfs://bafybeib7ulupka5wro2iz7qoqhrssjzf6eo3rbwaxbic5sjq3k3jmufwea',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: false,
    traits: [
      {
        name: 'Buddy type',
        value: 'Lemon',
      },
      {
        name: 'Horns',
        value: 'Gayal',
      },
      {
        name: 'Holdings',
        value: 'Soda',
      },
    ],
  },
  {
    name: 'loopy',
    description: 'optional',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t,tsU33UT3K2JTfLgHUo7hdzRhRe4wth885cqVbM8WLiq',
    owner_name: null,
    contract: null,
    token: '6JXs6vvpFUtWqGsxULU3cL4rKQ8ShvRPYayvHgAZbxJu',
    image: 'https://bafkreibf2guaujzixqmeti4se4z5nl27piwwalj5darxvaxaz47wmzoebi.ipfs.dweb.link?ext=gif',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: true,
    traits: [
      {
        name: 'darkblock-id',
        value: '-QxtmVRqywzZ4u33j5X912RZGoucuycoIGKbIdEmgbE',
      },
    ],
  },
  {
    name: 'bunny Test',
    description: 'this is longer',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t',
    owner_name: null,
    contract: null,
    token: '6Kba6aE3VcUP2HMBpET4Fs3Urqpgxtr6mDzq9WPrnbvJ',
    image: 'https://www.arweave.net/7YfeJEofOEyrgxhgYBD02yAKw6VXYj26jgNwPGUSFAM?ext=gif',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: true,
    traits: [
      {
        name: 'darkblock-id',
        value: 'Qr1Ofcw-W2tDeDJJM68QppibSfNM_bY_gAVWF7sC9wg',
      },
    ],
  },
  {
    name: 'Hi there',
    description: 'In the garden',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t',
    owner_name: null,
    contract: null,
    token: '744VUu9BsDn1d4C9Nw16AeaXVnLPZmUYxDjzzN399sXk',
    image: 'https://www.arweave.net/R0UEJic9ThkJgL1TRThS6mIEicZsKvliulqSjlvZ3eI?ext=PNG',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: true,
    traits: null,
  },
  {
    name: 'bunny4',
    description: 'longened',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t',
    owner_name: null,
    contract: null,
    token: '8JRGfCL3CB8qZ9b5YHpdXqexuFq2uJS65TMZdJTkekrt',
    image: 'https://www.arweave.net/ymUjyTIFto9ordzJfvcIX690wUo5xcIazynZ0LWTaU8?ext=gif',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: true,
    traits: [
      {
        name: 'darkblock-id',
        value: 'k6dUVCCJ6kAcxvJNIycpBSfkVopylti0rITnHkR8PdE',
      },
    ],
  },
  {
    name: '220324 Test 01',
    description: 'this is a long description',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t',
    owner_name: null,
    contract: null,
    token: '8yQ1UFip8WzjJqiMcr3foYaTZPKPrGcn2Ut9KPWdW83g',
    image: 'https://www.arweave.net/ZBfYgCeJDxgakBOlhbDIgC3fvsijRfaTsGKcLpBSpcU?ext=PNG',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: true,
    traits: null,
  },
  {
    name: 'Nice.',
    description: 'It was so nice.',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t',
    owner_name: null,
    contract: null,
    token: '9fxA59N3hxgGk4qkKknrNGJSjNyfLRNfNWHchqajJQts',
    image: 'https://www.arweave.net/gTLN0E53A0uSw3TTf_s_08l0xXDFHuSNduFR8aXoEMQ?ext=gif',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: true,
    traits: null,
  },
  {
    name: 'mint3',
    description: '',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t,tsU33UT3K2JTfLgHUo7hdzRhRe4wth885cqVbM8WLiq',
    owner_name: null,
    contract: null,
    token: '9to29w8aVK3n4xwEPwybqkaQb6x6iUWQHhi3vQjKHbpL',
    image: 'https://bafybeidhor352vl2oyy3fzknotr2mr5ix5xjnbo7ujaacldrvhi6uqh4rm.ipfs.dweb.link?ext=jpg',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: true,
    traits: [
      {
        name: 'darkblock-id',
        value: 'cMjcPAhK6Ctgo3iVE5YrQAag7AZrUpEERdAp4qkADBA',
      },
    ],
  },
  {
    name: 'Big Buck Bunny',
    description:
      'Tired of being picked on by Frankie the squirrel and his band of puny forest creatures, JC the bunny finally decides to fight back. - Big Buck Bunny is a short computer-animated comedy film, produced by the Blender Foundation and released as open-source film.',
    creator_name: null,
    creator_address: '6ruhJkff9PKEUpA53ZXnekXNBvnRZZfHRgAPFwLt8MLv,tsU33UT3K2JTfLgHUo7hdzRhRe4wth885cqVbM8WLiq',
    owner_name: null,
    contract: null,
    token: 'A4qFb1x6qeH9r5Vm4Qrt9qwT4a5bscY2DTf3UpvKEcoU',
    image: 'https://bafybeif5u3fdlhwkrxdr6gc6w5llafunbfuwp4kbzah6gq7w6zxmud57ri.ipfs.dweb.link?ext=png',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: false,
    traits: null,
  },
  {
    name: 'Happy men',
    description: 'These are happy men in Berlin',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t',
    owner_name: null,
    contract: null,
    token: 'Aqt1eQAjBpBtPnjTTGvZBURSdR4ZEH6HWYTLj6wvxbJL',
    image: 'https://www.arweave.net/PLRZI3_400kEd475t4yHGuHQyfREplecVOiQ8HUvjQk?ext=jpg',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: false,
    traits: null,
  },
  {
    name: 'DB in files test 2',
    description: 'Celebratory Solflare NFT for the Solflare X launch',
    creator_name: null,
    creator_address: '8Q9NhGn3aEHGxEqT6p6CUXpF8ivjM7FwocK15WNCZVb6',
    owner_name: null,
    contract: null,
    token: 'BEik4LVJc7mPGusEqTb28K53fwuxM3gYtZCNDi9xHXrg',
    image: 'https://www.arweave.net/vhzJJNLr9oRhV4P5lmuB17jU5-WBI9Omct6cdiCZshA?ext=png',
    platform: 'Solana',
    animation_url: 'https://www.arweave.net/efgh1234?ext=mp4',
    is_darkblocked: true,
    traits: [
      {
        name: 'web',
        value: 'yes',
      },
      {
        name: 'mobile',
        value: 'yes',
      },
      {
        name: 'extension',
        value: 'yes',
      },
    ],
  },
  {
    name: 'Mountains and Field',
    description: 'I did not take this photo',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t,tsU33UT3K2JTfLgHUo7hdzRhRe4wth885cqVbM8WLiq',
    owner_name: null,
    contract: null,
    token: 'CZyT2dXAbiCNorH21D2fobdR8xNxiKRoianyRzYxYUDw',
    image: 'https://bafybeigvw4e2yav7rzuwykc5armnl2tifyltfbayihqixomnhyk5nt5evy.ipfs.dweb.link?ext=jpg',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: false,
    traits: null,
  },
  {
    name: 'just trait',
    description: 'still no collection',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t',
    owner_name: null,
    contract: null,
    token: 'CqEzaR5P4oDV1EQvYtACYGzveFjXueqFUAUBpXf5ZQro',
    image: 'https://www.arweave.net/rKW518Mx7Tqir0lsnIrsnicNfMTkptRUxbS4kTiTJDU?ext=jpg',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: false,
    traits: [
      {
        name: 'Shade',
        value: 'Grey',
      },
    ],
  },
  {
    name: 'Ari + Darri @ NFTBER',
    description: 'Ari and Darri at NFT Berlin',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t',
    owner_name: null,
    contract: null,
    token: 'E7bmCK28SEmo6GXncaRZYG6Twj26XezLzDyp3wxUJQzW',
    image: 'https://www.arweave.net/zuhVtGU-qIPLycDbZA9h1NhPBCjysiXGmMGh3gAaaSI?ext=jpg',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: true,
    traits: null,
  },
  {
    name: 'Darkblock Video',
    description: 'Darkblock Video',
    creator_name: null,
    creator_address: 'H2JL9xvJXwVK6yobduQWYHc8dxU6GFFLNdaehVdgdbsu',
    owner_name: null,
    contract: null,
    token: 'EFHk6RfLLR8Cz2JseSz5y7QQY1w8vUGQZFiDjGZeDb1K',
    image: 'https://www.arweave.net/KWIGzH5e7mcDl3kDtJMwB2btotDKLUzta7diDOWvlSo?ext=jpg',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: false,
    traits: null,
  },
  {
    name: 'Buddy#1',
    description:
      'Oh you only have a 2D Bored Ape? Make your PFP more than just your next twitter avatar. (Darkblock PFP case study)',
    creator_name: null,
    creator_address: 'DBBd3jzbBA6xjfgLH4fkrTdinZRy2teMS2AuBQ6wYQhj',
    owner_name: null,
    contract: null,
    token: 'EHJg6CsR8aaMLymXbxP76a2Adg1ELLzWAsj1H6A3JePW',
    image: 'ipfs://bafybeib7ulupka5wro2iz7qoqhrssjzf6eo3rbwaxbic5sjq3k3jmufwea',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: false,
    traits: [
      {
        name: 'Buddy type',
        value: 'Lemon',
      },
      {
        name: 'Horns',
        value: 'Gayal',
      },
      {
        name: 'Holdings',
        value: 'Soda',
      },
    ],
  },
  {
    name: 'Collection Nft',
    description: 'i guess it was',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t',
    owner_name: null,
    contract: null,
    token: 'ERPDqCNHRGtDdHbaJSAevYki4neFb3Gmtuwce61bVHEH',
    image: 'https://www.arweave.net/d6G8AjQdddQWuXPN0T5L8nhgel-SjCF2guagQaJ0nZA?ext=PNG',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: true,
    traits: [
      {
        name: 'Shape',
        value: 'Square',
      },
      {
        name: 'Color',
        value: 'White',
      },
      {
        name: 'Shade',
        value: 'Grey',
      },
    ],
  },
  {
    name: 'BW Mountains',
    description: 'I did not take this photo either',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t,tsU33UT3K2JTfLgHUo7hdzRhRe4wth885cqVbM8WLiq',
    owner_name: null,
    contract: null,
    token: 'EZAQTYXYk2MnkJLiz5vyznkDT2vQPxxVQxZ7ux4G42tT',
    image: 'https://bafybeifkmt5angqb72tqgyp4ntyny5h2hcmygdy3anuifoqtitkbt4dhnm.ipfs.dweb.link?ext=jpg',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: true,
    traits: null,
  },
  {
    name: 'mint3',
    description: '',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t,tsU33UT3K2JTfLgHUo7hdzRhRe4wth885cqVbM8WLiq',
    owner_name: null,
    contract: null,
    token: 'EawKwi8Je23fkQRnCCbs1ECrqFKnUG5T5EebLAYuciSo',
    image: 'https://bafybeidhor352vl2oyy3fzknotr2mr5ix5xjnbo7ujaacldrvhi6uqh4rm.ipfs.dweb.link?ext=jpg',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: true,
    traits: [
      {
        name: 'darkblock-id',
        value: 'cMjcPAhK6Ctgo3iVE5YrQAag7AZrUpEERdAp4qkADBA',
      },
    ],
  },
  {
    name: 'Sample NFT',
    description: 'This is a test NFT with Darkblock',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t',
    owner_name: null,
    contract: null,
    token: 'F5cHLdKTYsy3833vggPYTfqAqaPdfc96vannofK29Diz',
    image: 'https://www.arweave.net/XbzOfjiBaQM5quSYE0r_Fdwg1Id5mam6_GmOlw7lTg8?ext=PNG',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: false,
    traits: null,
  },
  {
    name: 'bkiz',
    description: 'nothing',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t,tsU33UT3K2JTfLgHUo7hdzRhRe4wth885cqVbM8WLiq',
    owner_name: null,
    contract: null,
    token: 'FHwW2shMSECJzkJ5ZYUbp8AUcmNCwCozydhhRpmoYQjf',
    image: 'https://bafybeieyryht57micwkrh5lh7gxkowmpyqkyeu7ldvzefbcnaqstl5qeiy.ipfs.dweb.link?ext=png',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: true,
    traits: [
      {
        name: 'darkblock-id',
        value: '-QxtmVRqywzZ4u33j5X912RZGoucuycoIGKbIdEmgbE',
      },
    ],
  },
  {
    name: 'no traits',
    description: 'about the traits',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t',
    owner_name: null,
    contract: null,
    token: 'FurwxwKGENbxaTi6UmaTvB6qiu8rfUJet8w5JPQrT48y',
    image: 'https://www.arweave.net/yVOfXZKSJ1E7c7ENb097brTT67g5RgFUB0jcPiyox5A?ext=jpg',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: false,
    traits: null,
  },
  {
    name: 'mint3',
    description: '',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t,tsU33UT3K2JTfLgHUo7hdzRhRe4wth885cqVbM8WLiq',
    owner_name: null,
    contract: null,
    token: 'GHJsiCiL3TA9EvMKKGJeyjFsZYt2d1tBCpmhbVGp7xE1',
    image: 'https://bafybeidhor352vl2oyy3fzknotr2mr5ix5xjnbo7ujaacldrvhi6uqh4rm.ipfs.dweb.link?ext=jpg',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: true,
    traits: [
      {
        name: 'darkblock-id',
        value: 'cMjcPAhK6Ctgo3iVE5YrQAag7AZrUpEERdAp4qkADBA',
      },
    ],
  },
  {
    name: 'Test Loader SS',
    description: 'First Mint test',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t',
    owner_name: null,
    contract: null,
    token: 'GXJtxSMk4fU74Fc1EheKy9orZhNxySpW7ZU5pD6wKXAt',
    image: 'https://www.arweave.net/2uH4Tibn8dPnN1ET6gy6LPQWgws_cC0rmHw38ttzAO4?ext=gif',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: false,
    traits: null,
  },
  {
    name: 'bunny5',
    description: 'loooong',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t',
    owner_name: null,
    contract: null,
    token: 'GoYRLnh7hKnYBoWozaBu5NspZrRDLSJmwVTnzbiSYxaP',
    image: 'https://www.arweave.net/-MtVryy3cPZhZqdtCVPhz2ldBZk7P3-k3CqP-MrNLGE?ext=gif',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: true,
    traits: [
      {
        name: 'darkblock-id',
        value: 'UpzKyS7HZbiRwxSOAEhESnUbhROJ2pk0eQwus8KYyl0',
      },
    ],
  },
  {
    name: 'No DB here',
    description: 'Loooong description',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t',
    owner_name: null,
    contract: null,
    token: 'Grs1RF89VzvNzaNXisDQZvLEgqi2xLhn1c9HhbPfhitn',
    image: 'https://www.arweave.net/suzOAa4qgxCwPe8UeteaAcbaWD2Hc3uaKJvg3J4eoRw?ext=PNG',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: false,
    traits: null,
  },
  {
    name: 'Weird Science Comic',
    description: 'Weird Science Comic 01',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t',
    owner_name: null,
    contract: null,
    token: 'HtpRsvaoPh1EE8J338rnzNqy1pic7G8wrn4TVNXtE3C5',
    image: 'https://www.arweave.net/DMqLuzisbwtK20SGj_GsSaljpFpgGz0eQepvTccyNwk?ext=jpg',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: false,
    traits: null,
  },
  {
    name: 'mint3',
    description: '',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t,tsU33UT3K2JTfLgHUo7hdzRhRe4wth885cqVbM8WLiq',
    owner_name: null,
    contract: null,
    token: 'JCHYabmZ1DztsQgcvRQVwSqhdn1p8jRQGBHEBT1MqVJj',
    image: 'https://bafybeidhor352vl2oyy3fzknotr2mr5ix5xjnbo7ujaacldrvhi6uqh4rm.ipfs.dweb.link?ext=jpg',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: true,
    traits: [
      {
        name: 'darkblock-id',
        value: 'cMjcPAhK6Ctgo3iVE5YrQAag7AZrUpEERdAp4qkADBA',
      },
    ],
  },
  {
    name: 'dual screen',
    description: 'It has TWO screens',
    creator_name: null,
    creator_address: '9sUnEsLPa6uENMd6MBFMWYXAXDdTadj4nnxSoX93gg8t',
    owner_name: null,
    contract: null,
    token: 'fqJLkXAT8x1H2YShvpC6DE9BkLAwWQivpZea6rQApYF',
    image: 'https://www.arweave.net/98RNiFAF6SeMowAXofpq4_IetPu_dKDscgotBSN9-iE?ext=PNG',
    platform: 'Solana',
    animation_url: '',
    is_darkblocked: false,
    traits: null,
  },
]
